using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using SitebracoApi.Types;

namespace SitebracoApi.UmbracoDoctypes
{
    public class Content : ContentBase
    {
        public string content_title { get; set; }

        public DateTime? content_pubDate { get; set; }
        public DateTime? content_availableForPurchaseDate { get; set; }
        public double? content_price { get; set; }

        public string content_topicSegments { get; set; }
        public string content_abstract { get; set; }
        public string content_sourceFile { get; set; }
        public string content_sourceFileContentType { get; set; }
        public string content_sourceFileExtension { get; set; }
        public string content_sourceFileType { get; set; }

        public ContentEditorTemplateType content_sourceFileTypeEnum {
            get
            {
                ContentEditorTemplateType ret;
                Enum.TryParse<ContentEditorTemplateType>(content_sourceFileType, true, out ret);
                return ret;
            }
            set
            {
            }
        }

        public bool? content_sourceFileDownloadable { get; set; }

        public string content_autoGeneratedPdfFile { get; set; }
        public string content_autoExtractedContent { get; set; }
        public string content_autoExtractedRichtext { get; set; }

        
        public string content_spindoctor_class { get; set; }
        public string content_spindoctor_client { get; set; }
        public string content_spindoctor_focus { get; set; }
        public string content_spindoctor_primary { get; set; }
        public string content_spindoctor_role { get; set; }
        public string content_spindoctor_industry { get; set; }
        public string content_spindoctor_market { get; set; }
        public string content_spindoctor_topic { get; set; }
        public string content_spindoctor_region { get; set; }

    }
}
