//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSImportState
    {
        public int Id { get; set; }
        public System.Guid UniqueIdentifier { get; set; }
        public string Name { get; set; }
        public string ImportType { get; set; }
        public string ImportState { get; set; }
        public Nullable<bool> Recursive { get; set; }
        public Nullable<System.Guid> Parent { get; set; }
    }
}
