//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSImportScheduledItem
    {
        public int ScheduledItemId { get; set; }
        public int ScheduleldTaskId { get; set; }
        public System.DateTime ScheduledOn { get; set; }
        public Nullable<System.DateTime> ExecutedOn { get; set; }
        public Nullable<bool> InProgress { get; set; }
    }
}
