//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSImportCustomRelation
    {
        public int CustomRelationId { get; set; }
        public int UmbracoId { get; set; }
        public string Alias { get; set; }
        public string DataSourceKey { get; set; }
        public string RelatedId { get; set; }
    }
}
