//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSImportScheduledTask
    {
        public int ScheduleId { get; set; }
        public System.Guid ScheduleGUID { get; set; }
        public System.Guid ImportStateGUID { get; set; }
        public string ScheduledTaskName { get; set; }
        public string NotifyEmailAddress { get; set; }
        public string ExecuteEvery { get; set; }
        public string ExecuteDays { get; set; }
        public int ExecuteHour { get; set; }
        public int ExecuteMinute { get; set; }
        public Nullable<int> ImportAsUser { get; set; }
    }
}
