//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsMacroProperty
    {
        public int id { get; set; }
        public string editorAlias { get; set; }
        public int macro { get; set; }
        public int macroPropertySortOrder { get; set; }
        public string macroPropertyAlias { get; set; }
        public string macroPropertyName { get; set; }
    
        public virtual cmsMacro cmsMacro { get; set; }
    }
}
