//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsPropertyType
    {
        public cmsPropertyType()
        {
            this.cmsPropertyDatas = new HashSet<cmsPropertyData>();
            this.cmsTagRelationships = new HashSet<cmsTagRelationship>();
        }
    
        public int id { get; set; }
        public int dataTypeId { get; set; }
        public int contentTypeId { get; set; }
        public Nullable<int> propertyTypeGroupId { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public string helpText { get; set; }
        public int sortOrder { get; set; }
        public bool mandatory { get; set; }
        public string validationRegExp { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<cmsPropertyData> cmsPropertyDatas { get; set; }
        public virtual cmsPropertyTypeGroup cmsPropertyTypeGroup { get; set; }
        public virtual ICollection<cmsTagRelationship> cmsTagRelationships { get; set; }
    }
}
