//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsPreviewXml
    {
        public int nodeId { get; set; }
        public System.Guid versionId { get; set; }
        public System.DateTime timestamp { get; set; }
        public string xml { get; set; }
    }
}
