//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsPropertyTypeGroup
    {
        public cmsPropertyTypeGroup()
        {
            this.cmsPropertyTypes = new HashSet<cmsPropertyType>();
            this.cmsPropertyTypeGroup1 = new HashSet<cmsPropertyTypeGroup>();
        }
    
        public int id { get; set; }
        public Nullable<int> parentGroupId { get; set; }
        public int contenttypeNodeId { get; set; }
        public string text { get; set; }
        public int sortorder { get; set; }
    
        public virtual ICollection<cmsPropertyType> cmsPropertyTypes { get; set; }
        public virtual ICollection<cmsPropertyTypeGroup> cmsPropertyTypeGroup1 { get; set; }
        public virtual cmsPropertyTypeGroup cmsPropertyTypeGroup2 { get; set; }
    }
}
