//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsStylesheetProperty
    {
        public int nodeId { get; set; }
        public Nullable<bool> stylesheetPropertyEditor { get; set; }
        public string stylesheetPropertyAlias { get; set; }
        public string stylesheetPropertyValue { get; set; }
    }
}
