//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsTaskType
    {
        public cmsTaskType()
        {
            this.cmsTasks = new HashSet<cmsTask>();
        }
    
        public int id { get; set; }
        public string alias { get; set; }
    
        public virtual ICollection<cmsTask> cmsTasks { get; set; }
    }
}
