//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsTagRelationship
    {
        public int nodeId { get; set; }
        public int tagId { get; set; }
        public int propertyTypeId { get; set; }
    
        public virtual cmsPropertyType cmsPropertyType { get; set; }
        public virtual cmsTag cmsTag { get; set; }
    }
}
