//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public Component()
        {
            this.new_MetaClassPrimaryLookup = new HashSet<new_MetaClassPrimaryLookup>();
            this.VisitorComponents = new HashSet<VisitorComponent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProfilingAttributeId { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual ICollection<new_MetaClassPrimaryLookup> new_MetaClassPrimaryLookup { get; set; }
        public virtual ProfilingAttribute ProfilingAttribute { get; set; }
        public virtual ICollection<VisitorComponent> VisitorComponents { get; set; }
    }
}
