//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentSelector
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string Alias { get; set; }
        public int TypeCode { get; set; }
        public string PropertyBag { get; set; }
        public bool IsArchived { get; set; }
    }
}
