
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

    using System;
    using System.Collections.Generic;

    public partial class ENG_WidgetData
    {

        public ENG_WidgetData()
        {

            this.ENG_WidgetContent = new HashSet<ENG_WidgetContent>();

        }


        public int ID { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }



        public virtual ICollection<ENG_WidgetContent> ENG_WidgetContent { get; set; }

    }

}
