
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

using System;
    using System.Collections.Generic;
    
public partial class ENG_DashboardSettingColumn
{

    public ENG_DashboardSettingColumn()
    {

        this.reports = new HashSet<ENG_DashboardSettingReport>();

    }


    public long ID { get; set; }

    public int Order { get; set; }

    public int Size { get; set; }

    public Nullable<System.DateTime> CreateOn { get; set; }

    public Nullable<System.DateTime> ModifyOn { get; set; }

    public string ClientID { get; set; }

    public string Status { get; set; }



    public virtual ICollection<ENG_DashboardSettingReport> reports { get; set; }

}

}
