
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

using System;
    using System.Collections.Generic;
    
public partial class ENG_DashboardSettingView
{

    public int ReportOrder { get; set; }

    public string ReportName { get; set; }

    public Nullable<bool> ReportCollapse { get; set; }

    public int ColumnOrder { get; set; }

    public int ColumnSize { get; set; }

    public string ClientID { get; set; }

    public string Status { get; set; }

}

}
