
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

using System;
    using System.Collections.Generic;
    
public partial class ENG_Session
{

    public long ID { get; set; }

    public string SessionKey { get; set; }

    public string IPAddress { get; set; }

    public System.DateTime CreateOn { get; set; }

    public string CurrentAction { get; set; }

}

}
