
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

using System;
    using System.Collections.Generic;
    
public partial class ENG_Territory
{

    public ENG_Territory()
    {

        this.children = new HashSet<ENG_Territory>();

    }


    public int territoryID { get; set; }

    public Nullable<int> epriseID { get; set; }

    public string name { get; set; }

    public string boundaryType { get; set; }

    public string color { get; set; }

    public string note { get; set; }

    public string mapInfo { get; set; }

    public Nullable<System.DateTime> dateCreated { get; set; }

    public Nullable<int> parentId { get; set; }

    public Nullable<bool> leaf { get; set; }

    public string layers { get; set; }

    public string contactID { get; set; }

    public string clientId { get; set; }



    public virtual ICollection<ENG_Territory> children { get; set; }

}

}
