
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

using System;
    using System.Collections.Generic;
    
public partial class ENG_WidgetContent
{

    public ENG_WidgetContent()
    {

        this.ENG_WidgetContent_WidgetDataType_Lookup = new HashSet<ENG_WidgetContent_WidgetDataType_Lookup>();

    }


    public int ID { get; set; }

    public Nullable<int> WidgetId { get; set; }

    public string ClientID { get; set; }

    public Nullable<int> ContentId { get; set; }

    public string URL { get; set; }

    public Nullable<int> WidgetSettingID { get; set; }

    public string Position { get; set; }

    public Nullable<System.DateTime> CreateOn { get; set; }

    public Nullable<System.DateTime> ModifyOn { get; set; }



    public virtual ENG_WidgetSetting ENG_WidgetSetting { get; set; }

    public virtual ENG_Widget ENG_Widget { get; set; }

    public virtual ICollection<ENG_WidgetContent_WidgetDataType_Lookup> ENG_WidgetContent_WidgetDataType_Lookup { get; set; }

}

}
