
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

using System;
    using System.Collections.Generic;
    
public partial class ENG_Lead
{

    public long ID { get; set; }

    public string ClientID { get; set; }

    public string IPAddress { get; set; }

    public string MemberType { get; set; }

    public Nullable<System.DateTime> CreateOn { get; set; }

    public Nullable<System.DateTime> ModifyOn { get; set; }

    public string ViewerID { get; set; }

    public string Name { get; set; }

    public string Note { get; set; }

}

}
