
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

using System;
    using System.Collections.Generic;
    
public partial class ENG_DashboardSettingReport
{

    public long ID { get; set; }

    public Nullable<long> DashboardSettingColumnID { get; set; }

    public int Order { get; set; }

    public string Name { get; set; }

    public Nullable<System.DateTime> CreateOn { get; set; }

    public Nullable<System.DateTime> ModifyOn { get; set; }

    public Nullable<bool> Collapse { get; set; }



    public virtual ENG_DashboardSettingColumn ENG_DashboardSettingColumn { get; set; }

}

}
