
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

using System;
    using System.Collections.Generic;
    
public partial class ENG_UserSetting
{

    public int ID { get; set; }

    public string ClientId { get; set; }

    public Nullable<int> MouseMoveTracking { get; set; }

    public Nullable<int> MouseClickTracking { get; set; }

    public Nullable<int> PageViewsCounter { get; set; }

    public Nullable<int> PageViewsRankingLow { get; set; }

    public Nullable<int> PageViewsRankingMedium { get; set; }

    public Nullable<int> PageViewsRankingHigh { get; set; }

}

}
