
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

using System;
    using System.Collections.Generic;
    
public partial class ENG_WidgetSetting
{

    public ENG_WidgetSetting()
    {

        this.ENG_WidgetContent = new HashSet<ENG_WidgetContent>();

    }


    public int ID { get; set; }

    public string Color { get; set; }

    public Nullable<int> Width { get; set; }

    public Nullable<int> Height { get; set; }

    public string Name { get; set; }

    public Nullable<System.DateTime> CreateOn { get; set; }

    public Nullable<System.DateTime> ModifyOn { get; set; }



    public virtual ICollection<ENG_WidgetContent> ENG_WidgetContent { get; set; }

}

}
