
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

    using System;
    using System.Collections.Generic;

    public partial class ENG_WidgetLookupView
    {

        public string WidgetTypeName { get; set; }

        public string Name { get; set; }

        public string Color { get; set; }

        public int ID { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }

        public string ClientID { get; set; }

        public string URL { get; set; }

        public Nullable<int> Width { get; set; }

        public Nullable<int> Height { get; set; }

    }

}
