
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

using System;
    using System.Collections.Generic;
    
public partial class mt_ca_fsa_2014a_boundaries
{

    public int Id { get; set; }

    public Nullable<float> gid { get; set; }

    public string cfsauid { get; set; }

    public string pruid { get; set; }

    public string capabbr { get; set; }

    public string prename { get; set; }

    public Nullable<float> intptlat { get; set; }

    public Nullable<float> intptlon { get; set; }

    public Nullable<float> labellat { get; set; }

    public Nullable<float> labellon { get; set; }

    public Nullable<float> intptlatn { get; set; }

    public Nullable<float> intptlats { get; set; }

    public Nullable<float> intptlone { get; set; }

    public Nullable<float> intptlonw { get; set; }

    public Nullable<float> pop11 { get; set; }

    public Nullable<float> hu11 { get; set; }

    public Nullable<float> color { get; set; }

    public System.Data.Spatial.DbGeometry the_geom { get; set; }

}

}
