//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_MetaClassPrimaryLookup
    {
        public int ClassId { get; set; }
        public int PrimaryId { get; set; }
    
        public virtual Component Component { get; set; }
    }
}
