//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_OfficeTemplateVersion
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OfficeTemplateId { get; set; }
        public string TemplateBase64String { get; set; }
        public Nullable<System.DateTime> MarkDeleteOn { get; set; }
        public Nullable<System.Guid> Version { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual new_OfficeTemplate new_OfficeTemplate { get; set; }
    }
}
