
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitebracoApi.DbEntities
{

using System;
    using System.Collections.Generic;
    
public partial class NUTSBoundary
{

    public int Id { get; set; }

    public string NUTS_ID { get; set; }

    public int PolygonId { get; set; }

    public int SubPolygonId { get; set; }

    public string boundaryType { get; set; }

    public double SWLat { get; set; }

    public double SWLon { get; set; }

    public double NELat { get; set; }

    public double NELon { get; set; }

    public string Points { get; set; }

}

}
