//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public Segment()
        {
            this.VisitorSegments = new HashSet<VisitorSegment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int LifetimeSeconds { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual ICollection<VisitorSegment> VisitorSegments { get; set; }
    }
}
