//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggerRule
    {
        public TriggerRule()
        {
            this.VisitorTriggerRules = new HashSet<VisitorTriggerRule>();
        }
    
        public int Id { get; set; }
        public int TriggerId { get; set; }
        public int TriggerRuleTypeId { get; set; }
        public string PropertyBag { get; set; }
        public int MinimumHits { get; set; }
        public int LogicalOperatorFlags { get; set; }
        public int SortOrder { get; set; }
    
        public virtual TriggerRuleType TriggerRuleType { get; set; }
        public virtual Trigger Trigger { get; set; }
        public virtual ICollection<VisitorTriggerRule> VisitorTriggerRules { get; set; }
    }
}
