//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoServer
    {
        public int id { get; set; }
        public string address { get; set; }
        public string computerName { get; set; }
        public System.DateTime registeredDate { get; set; }
        public System.DateTime lastNotifiedDate { get; set; }
        public bool isActive { get; set; }
    }
}
