//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoUser
    {
        public umbracoUser()
        {
            this.cmsTasks = new HashSet<cmsTask>();
            this.cmsTasks1 = new HashSet<cmsTask>();
            this.umbracoUser2app = new HashSet<umbracoUser2app>();
            this.umbracoUser2NodeNotify = new HashSet<umbracoUser2NodeNotify>();
            this.umbracoUser2NodePermission = new HashSet<umbracoUser2NodePermission>();
        }
    
        public int id { get; set; }
        public bool userDisabled { get; set; }
        public bool userNoConsole { get; set; }
        public int userType { get; set; }
        public int startStructureID { get; set; }
        public Nullable<int> startMediaID { get; set; }
        public string userName { get; set; }
        public string userLogin { get; set; }
        public string userPassword { get; set; }
        public string userEmail { get; set; }
        public string userLanguage { get; set; }
    
        public virtual ICollection<cmsTask> cmsTasks { get; set; }
        public virtual ICollection<cmsTask> cmsTasks1 { get; set; }
        public virtual umbracoUserType umbracoUserType { get; set; }
        public virtual ICollection<umbracoUser2app> umbracoUser2app { get; set; }
        public virtual ICollection<umbracoUser2NodeNotify> umbracoUser2NodeNotify { get; set; }
        public virtual ICollection<umbracoUser2NodePermission> umbracoUser2NodePermission { get; set; }
    }
}
