//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoRelation
    {
        public int id { get; set; }
        public int parentId { get; set; }
        public int childId { get; set; }
        public int relType { get; set; }
        public System.DateTime datetime { get; set; }
        public string comment { get; set; }
    
        public virtual umbracoNode umbracoNode { get; set; }
        public virtual umbracoNode umbracoNode1 { get; set; }
        public virtual umbracoRelationType umbracoRelationType { get; set; }
    }
}
