//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoUserType
    {
        public umbracoUserType()
        {
            this.umbracoUsers = new HashSet<umbracoUser>();
        }
    
        public int id { get; set; }
        public string userTypeAlias { get; set; }
        public string userTypeName { get; set; }
        public string userTypeDefaultPermissions { get; set; }
    
        public virtual ICollection<umbracoUser> umbracoUsers { get; set; }
    }
}
