//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitebracoApi.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public Visitor()
        {
            this.VisitorComponents = new HashSet<VisitorComponent>();
            this.VisitorSegments = new HashSet<VisitorSegment>();
            this.VisitorTriggerRules = new HashSet<VisitorTriggerRule>();
        }
    
        public long Id { get; set; }
        public System.DateTime FirstVisit { get; set; }
        public System.DateTime LastVisit { get; set; }
        public int TrackingStatusCode { get; set; }
        public string UserHostAddress { get; set; }
        public string UserAgent { get; set; }
        public Nullable<long> FacebookId { get; set; }
        public string FacebookToken { get; set; }
    
        public virtual ICollection<VisitorComponent> VisitorComponents { get; set; }
        public virtual ICollection<VisitorSegment> VisitorSegments { get; set; }
        public virtual ICollection<VisitorTriggerRule> VisitorTriggerRules { get; set; }
    }
}
